#user
# POST http://localhost:3000/user
# Content-Type: application/json

# {
#     "username": "demo6",
#     "password": "demo6"
# }
# POST http://localhost:3000/user/2
# Content-Type: application/json

# {
#    "username": "demo2",
#    "password": "demo2"
# }
//DELETE User 
DELETE http://localhost:3000/user/2

#user
GET  http://localhost:3000/user/sesrch?q=d
Content-Type: application/json